firebase:
  project-id: ${FIREBASE_PROJECT_ID}

spring:
  application:
    name: products
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

security:
  cors:
    allowed-origins:
      - "http://localhost:5173"
      - "https://flower-store-cnik.onrender.com"
      - "https://eljardindecasablanca.shop/"
      - "https://eljardindecasablanca.shop"
      - "https://game-store-58h9.onrender.com"
      - "https://game-store-58h9.onrender.com/"


cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

gemini:
  api-key: ${GEMINI_API_KEY}
  model: gemini-2.5-flash
