spring:
  application:
    name: products
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:certs/public.pem
  datasource:
    url: jdbc:postgresql://dpg-d77qu9ruibrs73c55jd0-a.oregon-postgres.render.com/garden_3k71
    username: garden_3k71_user
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

security:
  cors:
    allowed-origins:
      - "http://localhost:3000"
      - "http://localhost:8080"
